---

- name: SH ARP
  hosts: cisco-routers
  gather_facts: false
  connection: local

  tasks:
      
  - name: Run sh arp
    ios_command: 
      commands: 
      - sh arp
      - sh ip int br
      provider: "{{cli}}"
    register: show_result

  - name: Show output (arp)
    debug: var=show_result.stdout_lines[0]

  - name: Show output (int)
    debug: var=show_result.stdout_lines[1]
